### ISSUE TITLE
kitchen fails with error 'vAPI: vapi.data.invalid: value does not have expected type'

### ISSUE THREAD

**Issue by seven10builder** [chef/kitchen-vcenter#22]
### Versions:
* Version of kitchen-vcenter: 1.2.1
* Version of test-kitchen: 1.19.2
* Version of chef: ChefDK 2.4.17

### Platform Details
* Version of vCenter: 6.5.0
* Version of ESXi: 6.5.0 (build 5969303)

### Scenario:
I am trying to start a test-kitchen instance on our local vcenter. I have previously tested this cookbook using ec2, but now want to run it locally.

### Steps to Reproduce:
I followed the steps listed in the current MASTER branch README.md. My .kitchen.yml file looks like the following
```yml
---
driver:
  name: vcenter
  vcenter_username: <%= ENV['VCENTER_USER'] || "administrator@vsphere.local" %>
  vcenter_password: <%= ENV['VCENTER_PASSWORD'] || "TOTALLY_NOT_MY_PASSWD" %>
  vcenter_host: 'VCENTER_HOST_ADDRESS'
  vcenter_disable_ssl_verify: true
  driver_config:
    datacenter: 'MY_DATACENTER_NAME'
    template: 'Ubuntu-16.04'
    targethost: 'MY_HOST_ADDRESS'
    resource_pool: 'DeployTest'

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: false
  sudo_command: sudo

verifier:
  name: inspec

transport:
  user: ubuntu
  password: password

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    data_bags_path: "test/integration/default/data_bags"
    encrypted_data_bag_secret_key_path: "test/integration/default/encrypted_data_bag_secret"

    run_list:
      - recipe[hydra-base::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes: {}
```

### Expected Result:
An instance is created and the various kitchen tasks are executed.

### Actual Result:
executed according to [this](https://github.com/chef/kitchen-vcenter/wiki/vCenter-Load-Path-error):
```
-----> Starting Kitchen (v1.19.2)
WARN: Unresolved specs during Gem::Specification.reset:
      rake (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
-----> Creating <default-ubuntu-1604>...
E, [2018-01-11T16:14:58.516537 #21252] ERROR -- vAPI: vapi.data.invalid: value does not have expected type
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [vapi.data.invalid: value does not have expected type] on default-ubuntu-1604
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```
