### ISSUE TITLE
Ability to create machine with Static IP and DNS settings. 

### ISSUE THREAD

**Issue by sam1el** [chef/kitchen-vcenter#72]
### Describe the Enhancement:
I would like to use this driver and be able to add customizations settings for setting systems up with Static IP and DNS configurations. This functionality was previously available in a kitchen-vsphere driver from a provisioning driver that is now in the boneyard
something similar to this

```      ssh:
        user: root
        paranoid: false
        password: password
        port: 22
      convergence_options:
      customization_spec:
        domain: local
        ipsettings:
          dnsServerList:
            - 8.8.8.8
            - 8.8.4.4
```

### Describe the Need:
Many customer I Have dealt with as well as when I was a customer of chef were forced to only use Static IPs even when doing test-kitchen for security reason. Because of this. I am unable to use this driver currently to test against corporate approved images for deployments., This makes is difficult to prove testing results in the pipeline as well as to security as they are not run against hardened images in house. 

### Current Alternative
No current alternative other than creating bento boxes for every customer.

### Can We Help You Implement This?:
Like many of the issues already filed. Adding customization features for vsphere/vcenter would greatly enhance the usability of the kitchen process for these customers.

**Comment by mkennedy85** [comment]
I would also like to see this. I have been able to use RbVmomi for this behavior outside of the `kitchen-vcenter` driver. It would look something similar to the below code, but there is some slightly strange behavior although it configures everything as expected, there is an error about `ipAddress` even though it is set on the VM.
- clone_vm.rb
```ruby
...
clone_spec = RbVmomi::VIM.VirtualMachineCloneSpec(
  location: relocate_spec,
  powerOn: options[:poweron] && options[:customize].nil?,
  template: false,
  customization: RbVmomi::VIM::CustomizationSpec.new(
    identity: RbVmomi::VIM::CustomizationLinuxPrep.new(
      domain: options[:customize][:dnsDomain],
      hostName: RbVmomi::VIM::CustomizationFixedName.new(
        name: name
      ),
      hwClockUTC: true,
      timeZone: options[:customize][:timeZone]'
    ),
    globalIPSettings: RbVmomi::VIM::CustomizationGlobalIPSettings.new(
      dnsServerList: options[:customize][:dnsServerList],
      dnsSuffixList: [
        options[:customize][:dnsDomain]
      ]
    ),
    nicSettingMap: [RbVmomi::VIM::CustomizationAdapterMapping.new(
      adapter: RbVmomi::VIM::CustomizationIPSettings.new(
        ip: RbVmomi::VIM::CustomizationFixedIp(
        ipAddress: options[:customize][:ipAddress]
      ),
        gateway: [
          options[:customize][:gateway]
        ],
        subnetMask: options[:customize][:subnetMask],
        dnsDomain: options[:customize][:dnsDomain]
      )
    )]
  )
)
...
```
- kitchen.yml
```yaml
...
driver:
      datacenter: 'DC'
      template: 'Templates/Current/CentOS_7.6_Template_1.0.0'
      cluster: 'dev'
      interface: 'Dev'
      poweron: true
      vm_name: test-kitchen-node1
      folder: 'Kitchen Tests'
      customize:
        ipAddress: '10.120.8.8'
        gateway: '10.120.8.1'
        subnetMask: '255.255.252.0'
        dnsDomain: 'example.com'
        timezone: 'US/Pacific'
        dnsServerList:
        - '7.7.7.7'
        - '8.8.8.8'
...
```
