### ISSUE TITLE
VapiStdErrorsUnauthenticated when i try to create a VM

### ISSUE THREAD

**Issue by devcrops-official** [chef/kitchen-vcenter#77]
### Versions:
* Version of kitchen-vcenter: 2.5.2
* Version of test-kitchen: 2.2.5
* Version of chef: 14

### Platform Details
* Version of vCenter: 6.5.0.23000

### Steps to Reproduce:
Run kitchen converge with kitchen.yml like this 
```
---
driver:
  name: vcenter
  vcenter_username: <%= ENV['VCENTER_USER'] %>
  vcenter_password: <%= ENV['VCENTER_PASSWORD'] %>
  vcenter_host:  vcenterdr.cervedgroup.com
  vcenter_disable_ssl_verify: true
  log_level: info
  customize:
    annotation: "Kitchen VM Test by <%= ENV['USER'] %> on <%= Time.now.to_s %>"

provisioner:
  name: chef_zero
  sudo_command: sudo
  deprecations_as_errors: true
  retry_on_exit_code:
    - 35 # 35 is the exit code signaling that the node is rebooting
  max_retries: 2
  wait_for_retry: 90
  log_level: info
  install_strategy: once # don't install again if an installation is detected.

verifier:
  name: inspec

platforms:
  - name: redhat-7
    driver:
      cluster: 'MyCluster' 
      resource_pool: 'low pool'
      clone_type: linked
      network_name: 'MyNetwork'
      datacenter: "MyDatacenter"
      template: 'CHEF/chef-base' 
      folder: 'CHEF'      
      vm_rollback: true
    transport:
      username: <%= ENV['LOCAL_USER'] %>
      password: <%= ENV['LOCAL_PASS'] %>

suites:
  - name: my-suite
    run_list:
      - recipe[mycookbook::default]
    verifier:
      inspec_tests:
        - test/integration/default
```

### Actual Result:
```
D      Message: Failed to complete #create action: [undefined method `empty?' for #<VSphereAutomation::VCenter::VapiStdErrorsUnauthenticated:0x0000000008072b48>] on zk-base-redhat-7
D      ----------------------
D      ------Backtrace-------
D      /home/jenkins/.chefdk/gem/ruby/2.6.0/gems/kitchen-vcenter-2.5.2/lib/kitchen/driver/vcenter.rb:384:in `get_cluster'
D      /home/jenkins/.chefdk/gem/ruby/2.6.0/gems/kitchen-vcenter-2.5.2/lib/kitchen/driver/vcenter.rb:93:in `create'
D      /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:485:in `public_send'
D      /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:485:in `block in perform_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:552:in `synchronize_or_call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:514:in `block in action'
D      /opt/chefdk/embedded/lib/ruby/2.6.0/benchmark.rb:293:in `measure'
D      /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:513:in `action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:485:in `perform_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:394:in `create_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
D      /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
D      /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:381:in `block in transition_to'
D      /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:380:in `each'
D      /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:380:in `transition_to'
D      /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:162:in `verify'
D      /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:191:in `block in test'
D      /opt/chefdk/embedded/lib/ruby/2.6.0/benchmark.rb:293:in `measure'
D      /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:187:in `test'
D      /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/command.rb:197:in `public_send'
D      /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/command.rb:197:in `run_action_in_thread'
D      /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
D      ----End Backtrace-----

```

It worked with this version of gems:
Successfully installed vsphere-automation-cis-0.1.0
Successfully installed vsphere-automation-appliance-0.1.0
Successfully installed vsphere-automation-content-0.1.0
Successfully installed vsphere-automation-vapi-0.1.0
Successfully installed vsphere-automation-vcenter-0.1.0
Successfully installed vsphere-automation-sdk-0.1.0
Successfully installed kitchen-vcenter-2.4.0

doesn't work now with these:
Successfully installed vsphere-automation-runtime-0.4.2
Successfully installed vsphere-automation-cis-0.4.2
Successfully installed vsphere-automation-appliance-0.4.2
Successfully installed vsphere-automation-content-0.4.2
Successfully installed vsphere-automation-vapi-0.4.2
Successfully installed vsphere-automation-vcenter-0.4.2
Successfully installed vsphere-automation-sdk-0.4.2
Successfully installed kitchen-vcenter-2.5.2
